# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: "build the compiled binary"
    cmds:
      - mkdir -p build
      - go build -o ./build/ ./cmd/web/
    silent: true
  test:
    desc: "run all unit tests"
    cmds:
      - go test ./... -cover
  lint:
    desc: "lint the code"
    cmds:
      - golangci-lint run
  run:
    desc: "runs the API"
    cmds:
      - go run ./cmd/web/
