# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: "build the compiled binary"
    cmds:
      - mkdir -p build
      - go build -o ./build/ .
  test:
    desc: "run all unit tests"
    cmds:
      - go test ./... -cover {{.CLI_ARGS}}
  lint:
    desc: "lint the code"
    cmds:
      - golangci-lint run
  run:
    desc: "runs the API"
    cmds:
      - go run . {{.CLI_ARGS}}
  pcc:
    desc: "runs several pre-commit checks and generates swagger documentation"
    cmds:
      - task: build
      - task: test
      - task: swag
      - task: lint
  swag:
    desc: "generate and format swagger documentation"
    cmds:
      - "swag init -o './api' -g './cmd/web/server.go' --parseDependency"
      - "swag fmt"
